theme = "transparency"

[editor]
bufferline = "never"
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "file-base-name", "version-control", "spinner"]
center = ["position"]
right = []
separator = "│"
mode.normal = "◎  NORMAL"
mode.insert = "▷  INSERT"
mode.select = "|Ξ SELECT"


[keys.insert]

j = { j = "normal_mode"}
A-j = "move_visual_line_down"
A-k = "move_visual_line_up"
A-l = "move_char_right"
A-h = "move_char_left"
